when:
  - event: push
    branch: master
  - event: pull_request
    branch: master

steps:
  test:
    image: rust
    environment:
      CARGO_HOME: /woodpecker/cache/cargo
      CARGO_TARGET_DIR: /woodpecker/cache/target
      PATH: /woodpecker/cache/cargo/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    commands:
      - cargo test
    volumes:
      - /woodpecker/cache/blsmr/cargo:/woodpecker/cache/cargo
      - /woodpecker/cache/blsmr/target:/woodpecker/cache/target
